### ISSUE TITLE
How do I use mods?

### ISSUE THREAD

**Issue by humblespace5534** [hadobedo/FunkiniOS#7]
Im a little confused, are mods available yet or have they not been added. If they are added can someone help me use them.

**Comment by Wondermine** [comment]
If you added your own mod, or replaced the assets conponents, it will make the sprites huge, or it will not work “unless you merged with filza”, it will be messed up for now, idk if the developer will add a mods combability.

**Comment by humblespace5534** [comment]
> If you added your own mod, or replaced the assets conponents, it will make the sprites huge, or it will not work “unless you merged with filza”, it will be messed up for now, idk if the developer will add a mods combability.

Thx for the reply, I tried (and failed) to jailbreak my phone with checkra1n a couple of minutes ago, so I might wait until checkra1n supports ios 14.4

**Comment by hadobedo** [comment]
> If you added your own mod, or replaced the assets conponents, it will make the sprites huge, or it will not work “unless you merged with filza”, it will be messed up for now, idk if the developer will add a mods combability.

Mod support will come after 0.2.8 (aka week 7) comes out, as the dev is working on a better, native way of allowing mods to be loaded. 

If you replace the files to use a mod in the current build, technically, the mod will 'work', but the sprites will be double size b/c of the method I used to lower RAM usage. I exported the sprite sheets at half size, and then resized them in game to double size so they're the proper size. Since the mods use the full size sprite sheets, the game will double the size even though they're already proper size, thus making them huge. I have an idea of how to fix this, but since week 7 is coming out so soon with proper mod loading, I'd rather fix mods & make them usable (maybe without a jailbreak, idk) in one fell swoop.

Hope that explains everything!
